### ISSUE TITLE
Poetry instillation failing to download all libraries

### ISSUE THREAD

**Issue by benku2** [deep-spin/tower-eval#23]
Python Version: 3.10.12
Poetry Version: 1.6.1
CUDA Version: release 12.2, V12.2.140
GPU: T4 GPU

It appears that installing on poetry is not correctly downloading all the libraries, despite claiming that it is. In `error.txt`, the `loguru` library appears to be missing, which we can confirm in `packages.txt`. However, from the small sample I grabbed in `install.txt`, loguru is claimed to be installed correctly by poetry. I have also attached a [Google Colab](https://colab.research.google.com/drive/1Py1mHKcsT_IqnWQLrj9IOnIpv_ULtBIY?usp=sharing) notebook that runs through the same process to repeat it. Running the notebook with any of the available GPUs results in the same error.

[error.txt](https://github.com/user-attachments/files/16266910/error.txt)
[install.txt](https://github.com/user-attachments/files/16266911/install.txt)
[packages.txt](https://github.com/user-attachments/files/16266912/packages.txt)

**Comment by zeppombal** [comment]
Hi @benku2, thanks for using tower-eval.
Have you made sure to activate your environment prior to running the bash script?

For example, in the terminal:
```bash
> source <YOUR_ENV>/bin/activate
> bash run_paper_benchmark.sh
```
I cannot access your notebook, unfortunately.

**Comment by benku2** [comment]
Thanks for the reply. Yes, I am attempting to utilize the environment while running the benchmark, but am still getting the issue of missing libraries. The Google Colab should now be accessible.

**Comment by zeppombal** [comment]
Thanks for sharing the colab. The repo is set up correctly; this was a Colab issue related to using python venvs.

I seem to have found the fix: if you want to use the environment in the notebook, you have to prefix every command with `source /content/tower-eval-env/bin/activate;` because Colab resets the shell at every cell (see [this](https://stackoverflow.com/questions/48512569/is-it-possible-to-activate-virtualenv-in-google-colab-bin-sh-1-source-not)).
For example,
```bash
!cd /content/tower-eval; source /content/tower-eval-env/bin/activate; bash run_paper_benchmark.sh
```

That said, I still got some huggingface credential errors after running the bash script, like:
```
OSError: You are trying to access a gated repo.
Make sure to have access to it at https://huggingface.co/meta-llama/Llama-2-70b-hf.
```
These are normal (you need to login to hugginface and accept the model's terms and conditions) but I'm not sure how you add credentials in a Colab notebook, because we don't work in that environment. I searching huggingface's documentaiton.

If you are looking to test the repository, I suggest running an example config that does not depend on a gated model; for example, one using our Tower models:

`python tower_eval/cli.py gen-eval --config configs/examples/gen_eval.yaml`
